# - name: ensure software-properties-common is installed
#   apt: name=software-properties-common state=latest

# - name: ensure ubuntu cloud keyring is installed
#   apt: name=ubuntu-cloud-keyring state=latest
  
# - name: Ensure ubuntu cloud archive for kilo is added
#   apt_repository: >-
#     repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/kilo main"
  
- name: Ensure system is upgraded (It can take a long time)
  apt: upgrade=yes update_cache=yes

- name: Ensure ntp is installed
  apt: name=ntp 
  notify: restart ntp

# - name: Ensure /etc/hosts is properly defined
#   copy: >-
#     src=etc/hosts
#     dest=/etc/hosts
#     owner=root
#     group=root
#     mode=0644
